-- create a product table having fields like prod_id, prod_name, prod_desc, price
create table product
(	prod_id integer unique not null,
	prod_name varchar(10),
	prod_desc text,
	price numeric(5,2)
);
-- insert some rows
insert into product(prod_id, prod_name, prod_desc, price) values
(
	1,'A','abc',10.00
),
(
	2,'B','def',20.00
),
(
	3,'C','ghi',30.00
),
(
	4,'D','jkl',40.00
),
(
	5,'E','mno',50.00
);

--add another column 'prod_category' in product table
alter table product
add column prod_category varchar(10);

--update prod_category for existing rows
update product
set prod_category = 'firstThree' where prod_id in(1,2,3);

update product
set prod_category = 'secondTwo' where prod_id in(4,5);

-- waq to fetch count of products in each category
select prod_category, count(*)
from product
group by prod_category;

-- display only those categories with more than 2 product
select prod_category, count(*)
from product
group by prod_category 
having count(*)>1;

-- sort based on count in ascending order
select prod_category, count(*) as count_product
from product
group by prod_category 
having count(*)>1
order by count_product asc;

-- waq to fetch product having second highest price
select prod_name, price 
from product 
where price = (
	select max(price) 
	from product 
	where price < (
			select max(price)
			from product)
	);


-- update the price of all the firstThree items so that the new price is 10% less than the original price
update product
set price = price-price*0.10 
where prod_category = 'firstThree';

-- delete the products whose price is less than the average price of all the products
delete from product where price > 
(select avg(price) from product);

-- delete product category wise whose price is less than the average price of all the products
--9 and 40 should get deleted

delete from product where prod_name in(
select p1.prod_name from product p1
where price <
(select avg(price)
from product p2
where p1.prod_category=p2.prod_category));

-- create an orders table having fields as ord_id, ord_type and prod_id as foreign key 
-- Also ensure that whenever data changes in the parent table, it should get reflected in the child table
create table orders
(
ord_id serial primary key,
ord_type varchar(20),
ord_date date,
prod_id integer,
foreign key (prod_id) references product(prod_id)
on delete cascade
on update cascade
);

-- add 5 rows in the orders table
insert into orders
(ord_type, ord_date, prod_id)
values
('newOrder', '2026-02-17',1)
('repeatOrder','2026-03-17',2),
('newOrder','2026-04-17',3),
('repeatOrder','2026-05-17',4),
('newOrder','2026-06-17',5);


-- fetch the product which has most number of orders
select *
from product
where prod_id =(select prod_id
					from orders
					group by prod_id
					order by count(*) desc
					limit 1
					)


--delete a product from product table and make sure thr order entry is also deleting
delete from product
where prod_id = 5;



--- INDEX
--primary key by default act as an index but user will search by the product name so we need create ian index on product name
-- without index suppose we have 1000 records then even if the searching result at the 10th rows but the query wont stop there it will just execute upto 1000 rows. thats why indexing is important but it is costly cuz internally it will create an another table for referencing
create index idx_prodname on product(prod_name);


--JOINS
--Inner join -> fetching the common records

--- fetch order details along with the product name and price
select o.ord_id, o.ord_type, o.ord_date, p.prod_id, p.prod_name, p.price
from orders o inner join product p
on o.ord_id = p.prod_id;

--- total revenue generated by each product
select p.prod_name, count(o.ord_id), sum(price)
from product p inner join orders o
on p.prod_id = o.prod_id
group by p.prod_name;

--- product that have never been ordered
select p.prod_name, p.price 
from product p left outer join orders o
on p.prod_id = o.ord_id
where o.ord_id is null 
;

--- Products with more repeat orders than new orders
select p.prod_name, count(*)
from product p inner join orders o
on p.prod_id = o.prod_id
where o.ord_type = 'repeatOrder'
group by p.prod_name
order by count(*) desc
limit 1
;

--- top 3 products based on number of orders

explain select p.prod_name, count(*)
from product p inner join orders o
on p.prod_id = o. prod_id
group by p.prod_name
order by count(*) desc
limit 3;

--- Total revenue from 'new' and 'repeat' orders separately
select o.ord_type, sum(price)
from product p inner join orders o
on p.prod_id = o.prod_id
group by o.ord_type;


-- Month-wise total revenue
select to_char(o.ord_date, 'MM') as months, sum(price)
from product p inner join orders o
on p.prod_id = o.prod_id
group by months;


select * from product;

select * from orders;

--- FUNCTIONS
--creating a function
create or replace function add_numbers(a int, b int)
returns int
as $$
begin
	return a+b;
end;
$$ language plpgsql;

--- calling the function
select add_numbers(23, 65);


--- create a function that takes the product name as input and returns the price
create or replace function product_price_info(prod_nm varchar(2))
returns int
as $$
declare prod_price int;
begin
select price into prod_price from product where prod_name = prod_nm;
return prod_price;
end;
$$ language plpgsql;

select product_price_info('A');

--- create a function that return a table 
create or replace function get_table()
returns table(id int, name varchar(20))
as $$
begin
return query select prod_id, prod_name from product;
end;
$$ language plpgsql;

select * from get_table();

--- PROCEDURE
--procedure doesnt return anything
--use case : insert, update , delete

--write a proedure that takes product fields as input and add a new row in product table
create or replace procedure insert_row(prod_id int, prod_name varchar(10), prod_desc text, price numeric, product_category varchar(10))
as $$
begin
insert into product values (prod_id, prod_name, prod_desc, price, product_category);
end;
$$ language plpgsql;

call insert_row(6, 'F', 'pqr', 60, 'thirdOne');


--write a procedure that takes prod id and apply discounted price on that product
create or replace procedure discounted_price(prd_id int, discounted_price int)
as $$
begin
update product set price = price - (price*discounted_price)/100 where prod_id = prd_id;
end;
$$ language plpgsql;

call discounted_price(4,10);



--Triggers
-- Create accounts table having id, name and balance field
-- Create account_audit table having account_id, old_balance, new_balance, changed_on fields

create table account
(
id serial primary key,
name varchar(20),
balance numeric
);

create table account_audit
(
account_id int,
old_balance numeric,
new_balance numeric,
changed_on timestamp default current_timestamp
);

-- Trigger function
create or replace function log_balance_update()
returns trigger
as $$
begin
insert into account_audit(account_id, old_balance, new_balance)
values (old.id, old.balance, new.balance);

return new;
end;
$$ language plpgsql;

--create trigger
create trigger balance_update_trigger
after update on account
for each row
when (old.balance is distinct from new.balance)
execute function log_balance_update();

--insert 2 rows in account table
insert into account 
(name, balance)
values
('mithun', 20),
('sagar', 40);

--update one record balance on account table. it will execute the trigger internally and add record inside account_audit table.
update account
set balance = 100 where id = 1;


select * from account;
select * from account_audit;

